/*
 * SPDX-License-Identifier: GPL-2.0-only
 *
 * Generated by tools/export_temporal_t2_shadow_runtime_v1.py.
 */

#ifndef TEMPORAL_T2_DISTRIBUTION_MODEL_DATA_V1_H
#define TEMPORAL_T2_DISTRIBUTION_MODEL_DATA_V1_H

#include "temporal-t2-distribution-model-evaluator.h"

#include <array>
#include <cstdint>
#include <span>
#include <string_view>

namespace ns3
{
namespace temporal_t2_distribution_model_v1
{

/** One fitted median imputer and appended missing indicators. */
struct Imputer
{
    std::span<const double> medians; ///< Per-feature training medians.
    std::span<const uint16_t> missingIndicatorRawFeatures; ///< Indicator sources.
};

/** One node in a fitted histogram-gradient-boosting tree. */
struct Node
{
    double value; ///< Leaf raw-score contribution.
    double threshold; ///< Numeric split threshold.
    uint16_t feature; ///< Imputed feature index.
    uint16_t left; ///< Left child relative to the tree root.
    uint16_t right; ///< Right child relative to the tree root.
    bool missingLeft; ///< Whether a missing value follows the left child.
    bool leaf; ///< Whether this node is a leaf.
};

/** Location and class of one tree in a concatenated node array. */
struct Tree
{
    uint32_t offset; ///< First node in the classifier node array.
    uint16_t count; ///< Number of nodes in the tree.
    uint8_t classIndex; ///< Output class updated by the tree.
};

/** One fitted six-class HGB completion-distribution head. */
struct MulticlassClassifier
{
    Imputer imputer; ///< Fitted arm-specific imputer.
    std::span<const Node> nodes; ///< Concatenated tree nodes.
    std::span<const Tree> trees; ///< Tree locations and output classes.
    std::array<double, 6> baseline; ///< Initial raw class scores.
    uint32_t trainingCount; ///< Rows used to fit this arm.
    double dirichletAlpha; ///< Per-class smoothing pseudocount.
};

/** Reachable prefix of one exact marginal reward-density curve. */
struct ShadowCurve
{
    std::span<const double> densityDescending; ///< Sorted positive densities.
    uint16_t trainingRunCount; ///< Contributing opened run groups.
    bool complete; ///< Whether the stored prefix is the complete curve.
};

/** Congestion state and three deployable curves for one time bin. */
struct ReferenceBin
{
    std::array<double, 2> congestionCutpoints; ///< Frozen tertile boundaries.
    std::array<ShadowCurve, 3> congestionCurves; ///< Regime-specific curves.
};

/** Generated runtime metadata. */
struct Metadata
{
    TemporalT2DistributionModelProvenance provenance; ///< Source closure.
    std::string_view featureFamily; ///< Selected 308-feature family.
    std::string_view featureAdapter; ///< Numeric input adapter.
    std::string_view modelSpecId; ///< Selected HGB specification.
    std::string_view objective; ///< Primary allocation benefit.
    std::string_view frameGate; ///< Caller-owned frame gate.
    double canonicalPFrameReservationUs; ///< Frozen action reservation.
    double maximumRepayableCreditUs; ///< Maximum reachable resource state.
    uint32_t timeBinWidthUs; ///< Fixed shadow-reference time bin.
};

/** @return Ordered raw feature names. */
std::span<const std::string_view> GetFeatureNames();

/** @return Fitted no-action completion head. */
const MulticlassClassifier& GetControlClassifier();

/** @return Fitted full-copy completion head. */
const MulticlassClassifier& GetFullCopyClassifier();

/** @return Frozen deployable congestion reference bins. */
std::span<const ReferenceBin> GetReferenceBins();

/** @return Generated runtime metadata. */
const Metadata& GetMetadata();

} // namespace temporal_t2_distribution_model_v1
} // namespace ns3

#endif // TEMPORAL_T2_DISTRIBUTION_MODEL_DATA_V1_H
